language: java
jdk:
  - openjdk7
sudo: false
env:
  global:
    _JAVA_OPTIONS="-Xmx1g -XX:MaxPermSize=256m"

cache:
  directories:
    - $HOME/.m2

notifications:
  email: false

before_install:
  - ulimit -u 65535

script: ./gradlew --parallel -PtestForks=2 test itest -s

after_success:
  - ./gradlew jacocoReport coveralls
